# Generated by Django 4.1.13 on 2023-12-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='General', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='No description provided', max_length=5000),
        ),
    ]
